---
- name: Install Java SDK
  yum:
    name: java-11-openjdk-devel
    state: latest
  tags:
    - jenkins

- name: Install Jenkins yum repository
  yum_repository:
    name: jenkins
    description: Jenkins-stable
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgcheck: yes
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  tags:
    - jenkins

- name: Install Jenkins
  yum:
    name: jenkins
    state: present
  tags:
    - jenkins
